stages:
  - build
  - test
  - run

# Gradle

.gradle:
  image: gradle:8.2-jdk17
  variables:
    GRADLE_OPTS: -Dorg.gradle.daemon=false

.gradle:compile:
  extends: .gradle
  stage: build
  script:
    - gradle --build-cache :$PROJECT:build -x :$PROJECT:check :$PROJECT:dependencies

.gradle:test:
  stage: test
  script:
    - gradle --build-cache :$PROJECT:check

# Projects

include:
  - local: /aoc-commons/.gitlab-ci.yml
  - local: /2023/kotlin/.gitlab-ci.yml
  - local: /2022/kotlin/.gitlab-ci.yml
  - local: /2021/kotlin/.gitlab-ci.yml
  - local: /2020/kotlin/.gitlab-ci.yml
  - local: /2020/lua/.gitlab-ci.yml
  - local: /2015/.gitlab-ci.yml
