stages:
  - commons:build
  - commons:test
  - commons:deploy
  - build
  - test
  - run

# Gradle

.gradle:
  image: gradle:7-jdk17
  variables:
    GRADLE_OPTS: -Dorg.gradle.daemon=false

.gradle:compile:
  extends: .gradle
  stage: build
  needs:
    - job: commons:kotlin:deploy
      optional: true
  dependencies:
    - commons:kotlin:deploy
  script:
    - gradle --build-cache dependencies build -x check

.gradle:test:
  stage: test
  script:
    - gradle --build-cache check

# Projects

include:
  - local: /aoc-commons/.gitlab-ci.yml
  - local: /2022/kotlin/.gitlab-ci.yml
  - local: /2021/kotlin/.gitlab-ci.yml
  - local: /2020/kotlin/.gitlab-ci.yml
  - local: /2020/lua/.gitlab-ci.yml
  - local: /2015/.gitlab-ci.yml
