stages:
  - build
  - test
  - run

# Gradle

.gradle:
  image: registry.sbmf21.nl/infra/containers/gradle:8-jdk21
  variables:
    GRADLE_OPTS: -Dorg.gradle.daemon=false

.gradle:compile:
  extends: .gradle
  stage: build
  script:
    - gradle --build-cache :$PROJECT:build -x :$PROJECT:check :$PROJECT:dependencies

.gradle:test:
  stage: test
  script:
    - gradle --build-cache :$PROJECT:check

# Lua
.lua:
  image: registry.sbmf21.nl/infra/containers/lua:latest

# Projects

include:
  - local: /2015/java/.gitlab-ci.yml
  - local: /2016/kotlin/.gitlab-ci.yml
  - local: /2020/kotlin/.gitlab-ci.yml
  - local: /2020/lua/.gitlab-ci.yml
  - local: /2021/kotlin/.gitlab-ci.yml
  - local: /2022/kotlin/.gitlab-ci.yml
  - local: /2023/kotlin/.gitlab-ci.yml
  - local: /2024/kotlin/.gitlab-ci.yml
  - local: /aoc-commons/.gitlab-ci.yml
