variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Maven

.maven:
  image: maven:latest

.maven:test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

.maven:compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

# 2015

.maven2015:
  extends: .maven
  before_script:
    - cd 2015
  cache:
    key: 'maven:2015'
    paths:
      - 2015/.m2/repository/
      - 2015/target/

compile2015:
  extends:
    - .maven2015
    - .maven:compile

test2015:
  extends:
    - .maven2015
    - .maven:test
  needs:
    - compile2015

#2020

.maven2020:
  extends: .maven
  before_script:
    - cd 2020/kotlin
  cache:
    key: 'maven:2020'
    paths:
      - 2020/kotlin/.m2/repository/
      - 2020/kotlin/target/

compile2020:
  extends:
    - .maven2020
    - .maven:compile

test2020:
  extends:
    - .maven2020
    - .maven:test
  needs:
    - compile2020
