stages:
  - commons:build
  - commons:test
  - commons:deploy
  - build
  - test
  - run

# Gradle

.gradle:
  image: openjdk:17.0.2-jdk-slim

.gradle:compile:
  extends: .gradle
  stage: build
  needs:
    - job: commons:kotlin:deploy
      optional: true
  dependencies:
    - commons:kotlin:deploy
  script:
    - ./gradlew clean dependencies build -x check

.gradle:test:
  stage: test
  script:
    - ./gradlew check

# Projects

include:
  - local: /aoc-commons/.gitlab-ci.yml
  - local: /2022/kotlin/.gitlab-ci.yml
  - local: /2021/kotlin/.gitlab-ci.yml
  - local: /2020/kotlin/.gitlab-ci.yml
  - local: /2020/lua/.gitlab-ci.yml
  - local: /2015/.gitlab-ci.yml
