stages:
  - build
  - test
  - run

# Maven

.maven:
  image: maven:latest
  variables:
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.maven:compile:
  stage: build
  needs: []
  dependencies:
    - commons:kotlin:deploy
  script:
    - mvn $MAVEN_CLI_OPTS compile package -Dmaven.test.skip=true

.maven:test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

# Lua

.lua:
  image: registry.gitlab.com/switchware/containers/lua:latest

# Projects

include:
 - local: /ci/kt-commons.yml
 - local: /ci/2015/java.yml
 - local: /ci/2020/kotlin.yml
 - local: /ci/2020/lua.yml
 - local: /ci/2021/kotlin.yml
#  - local: /ci/2021/ada.yml
