variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.test:
  stage: test

# Maven

.maven:
  image: maven:latest

.maven:test:
  extends: .test
  script:
    - mvn $MAVEN_CLI_OPTS test

.maven:compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

# 2015

.maven2015:
  extends: .maven
  before_script:
    - cd 2015
  cache:
    key: 'maven:2015'
    paths:
      - 2015/.m2/repository/
      - 2015/target/

compile:java:2015:
  extends:
    - .maven2015
    - .maven:compile

test:java:2015:
  extends:
    - .maven2015
    - .maven:test
  needs:
    - compile:java:2015

#2020

test:lua:2020:
  image: superpaintman/lua:5.3.3
  extends: .test
  needs: []
  before_script:
    - cd 2020/lua
  script:
    - ./test.sh

.maven2020:
  extends: .maven
  before_script:
    - cd 2020/kotlin
  cache:
    key: 'maven:2020'
    paths:
      - 2020/kotlin/.m2/repository/
      - 2020/kotlin/target/

compile:kotlin:2020:
  extends:
    - .maven2020
    - .maven:compile

test:kotlin:2020:
  extends:
    - .maven2020
    - .maven:test
  needs:
    - compile:kotlin:2020
