.2015:java:
  extends: .gradle
  only:
    changes:
      - 2015/**/*
  before_script:
    - cd 2015
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    key: '2015:java'
    policy: pull
    paths:
      - 2015/.gradle/caches
      - 2015/build

2015:java:compile:
  extends:
    - .2015:java
    - .gradle:compile
  cache:
    key: '2015:java'
    policy: pull-push
    paths:
      - 2015/.gradle/caches
      - 2015/build

2015:java:test:
  extends:
    - .2015:java
    - .gradle:test
  dependencies:
    - 2015:java:compile
  needs:
    - 2015:java:compile
  artifacts:
    reports:
      junit: 2015/build/test-results/test/TEST-*.xml

2015:java:run:
  extends: .2015:java
  stage: run
  dependencies:
    - 2015:java:compile
  needs:
    - 2015:java:compile
    - 2015:java:test
  script:
    - java -jar build/libs/aoc2015-shaded.jar --hide
