variables:
  PROJECT: '2020'

.2020:kotlin:caches:
  key: '2020:kotlin'
  paths:
    - .gradle/caches
    - 2020/kotlin/build

.2020:kotlin:
  extends: .gradle
  only:
    changes:
      - 2020/kotlin/**/*
  cache:
    key: !reference [.2020:kotlin:caches, key]
    policy: pull
    paths: !reference [.2020:kotlin:caches, paths]

2020:kotlin:compile:
  extends:
    - .2020:kotlin
    - .gradle:compile
  cache:
    key: !reference [.2020:kotlin:caches, key]
    policy: pull-push
    paths: !reference [.2020:kotlin:caches, paths]

2020:kotlin:test:
  extends:
    - .2020:kotlin
    - .gradle:test
  dependencies:
    - 2020:kotlin:compile
  needs:
    - 2020:kotlin:compile
  artifacts:
    reports:
      junit: 2020/kotlin/build/test-results/test/TEST-*.xml

2020:kotlin:run:
  extends: .2020:kotlin
  stage: run
  dependencies:
    - 2020:kotlin:compile
  needs:
    - 2020:kotlin:compile
    - 2020:kotlin:test
  script:
    - java -jar 2020/kotlin/build/libs/aoc2020-shaded.jar --hide
