.2020:kotlin:
  extends: .gradle
  only:
    changes:
      - 2020/kotlin/**/*
  before_script:
    - cd 2020/kotlin
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    key: '2020:kotlin'
    policy: pull
    paths:
      - 2020/kotlin/.gradle/caches
      - 2020/kotlin/build

2020:kotlin:compile:
  extends:
    - .2020:kotlin
    - .gradle:compile
  cache:
    key: '2020:kotlin'
    policy: pull-push
    paths:
      - 2020/kotlin/.gradle/caches
      - 2020/kotlin/build

2020:kotlin:test:
  extends:
    - .2020:kotlin
    - .gradle:test
  dependencies:
    - 2020:kotlin:compile
  needs:
    - 2020:kotlin:compile
  artifacts:
    reports:
      junit: 2020/kotlin/build/test-results/test/TEST-*.xml

2020:kotlin:run:
  extends: .2020:kotlin
  stage: run
  dependencies:
    - 2020:kotlin:compile
  needs:
    - 2020:kotlin:compile
    - 2020:kotlin:test
  script:
    - java -jar build/libs/aoc2020-shaded.jar --hide
