.2022:kotlin:caches:
  key: '2022:kotlin'
  paths:
    - .gradle
    - aoc-commons/build
    - 2022/kotlin/build

.2022:kotlin:
  extends: .gradle
  only:
    changes:
      - aoc-commons/**/*
      - 2022/kotlin/**/*
  cache:
    key: !reference [ .2022:kotlin:caches, key ]
    policy: pull
    paths: !reference [ .2022:kotlin:caches, paths ]

2022:kotlin:compile:
  extends:
    - .2022:kotlin
    - .gradle:compile
  variables:
    PROJECT: '2022'
  cache:
    key: !reference [ .2022:kotlin:caches, key ]
    policy: pull-push
    paths: !reference [ .2022:kotlin:caches, paths ]

2022:kotlin:test:
  extends:
    - .2022:kotlin
    - .gradle:test
  variables:
    PROJECT: '2022'
  dependencies:
    - 2022:kotlin:compile
  needs:
    - 2022:kotlin:compile
  artifacts:
    reports:
      junit: 2022/kotlin/build/test-results/test/TEST-*.xml

2022:kotlin:run:
  extends: .2022:kotlin
  stage: run
  dependencies:
    - 2022:kotlin:compile
  needs:
    - 2022:kotlin:compile
    - 2022:kotlin:test
  script:
    - java -jar 2022/kotlin/build/libs/aoc2022-shaded.jar
