.commons:kotlin:
  extends: .gradle
  only:
    changes:
      - aoc-commons/**/*
  before_script:
    - cd aoc-commons
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    key: 'commons:kotlin'
    policy: pull
    paths:
      - aoc-commons/.gradle/caches
      - aoc-commons/build

commons:kotlin:compile:
  extends:
    - .commons:kotlin
    - .gradle:compile
  cache:
    key: 'commons:kotlin'
    policy: pull-push
    paths:
      - aoc-commons/.gradle/caches
      - aoc-commons/build

commons:kotlin:test:
  extends:
    - .commons:kotlin
    - .gradle:test
  dependencies:
    - commons:kotlin:compile
  needs:
    - commons:kotlin:compile
  artifacts:
    reports:
      junit: aoc-commons/build/test-results/test/TEST-*.xml
  script:
    - gradle --build-cache check
