.commons:kotlin:
  extends: .maven
  only:
    refs:
      - master
    changes:
      - aoc-commons/**/*
  cache:
    key: 'maven:commons'
    policy: pull
    paths:
      - aoc-commons/.m2/repository/
      - aoc-commons/target/
  before_script:
    - cd aoc-commons

commons:kotlin:deploy:
  extends: .commons:kotlin
  stage: build:commons
  cache:
    key: 'maven:commons'
    policy: pull-push
    paths:
      - aoc-commons/.m2/repository/
      - aoc-commons/target/
  artifacts:
    paths:
      - aoc-commons/.m2/repository/nl/sbmf21/adventofcode.common
  script:
    - mvn deploy install -s ci_settings.xml

commons:kotlin:test:
  extends:
    - .commons:kotlin
    - .maven:test
  dependencies:
    - commons:kotlin:deploy
  needs:
    - commons:kotlin:deploy
  artifacts:
    reports:
      junit: aoc-commons/target/surefire-reports/TEST-*.xml
