.commons:kotlin:caches:
  key: 'commons:kotlin'
  paths:
    - .gradle/caches
    - aoc-commons/build

.commons:kotlin:
  extends: .gradle
  only:
    changes:
      - aoc-commons/**/*
  cache:
    key: !reference [ .commons:kotlin:caches, key ]
    policy: pull
    paths: !reference [ .commons:kotlin:caches, paths ]

commons:kotlin:compile:
  extends:
    - .commons:kotlin
    - .gradle:compile
  variables:
    PROJECT: 'aoc-commons'
  cache:
    key: !reference [ .commons:kotlin:caches, key ]
    policy: pull-push
    paths: !reference [ .commons:kotlin:caches, paths ]

commons:kotlin:test:
  extends:
    - .commons:kotlin
    - .gradle:test
  variables:
    PROJECT: 'aoc-commons'
  dependencies:
    - commons:kotlin:compile
  needs:
    - commons:kotlin:compile
  artifacts:
    reports:
      junit: aoc-commons/build/test-results/test/TEST-*.xml
