.2023:kotlin:caches:
  key: '2023:kotlin'
  paths:
    - .gradle
    - aoc-commons/build
    - 2023/kotlin/build

.2023:kotlin:
  extends: .gradle
  only:
    changes:
      - aoc-commons/**/*
      - 2023/kotlin/**/*
  cache:
    key: !reference [ .2023:kotlin:caches, key ]
    policy: pull
    paths: !reference [ .2023:kotlin:caches, paths ]

2023:kotlin:compile:
  extends:
    - .2023:kotlin
    - .gradle:compile
  variables:
    PROJECT: '2023'
  cache:
    key: !reference [ .2023:kotlin:caches, key ]
    policy: pull-push
    paths: !reference [ .2023:kotlin:caches, paths ]

2023:kotlin:test:
  extends:
    - .2023:kotlin
    - .gradle:test
  variables:
    PROJECT: '2023'
  dependencies:
    - 2023:kotlin:compile
  needs:
    - 2023:kotlin:compile
  artifacts:
    reports:
      junit: 2023/kotlin/build/test-results/test/TEST-*.xml

2023:kotlin:run:
  extends: .2023:kotlin
  stage: run
  dependencies:
    - 2023:kotlin:compile
  needs:
    - 2023:kotlin:compile
    - 2023:kotlin:test
  script:
    - java -jar 2023/kotlin/build/libs/aoc2023-shaded.jar --hide
