.2020:lua:
  image: registry.gitlab.com/switchware/containers/lua:latest
  only:
    changes:
      - 2020/lua/**/*
  before_script:
    - cd 2020/lua/src

2020:lua:test:
  extends: .2020:lua
  stage: test
  needs: []
  script:
    - lua test.lua

2020:lua:run:
  extends: .2020:lua
  stage: run
  needs:
    - 2020:lua:test
  script:
    - lua main.lua
