variables:
  PROJECT: '2021'

.2021:kotlin:caches:
  key: '2021:kotlin'
  paths:
    - .gradle
    - 2021/kotlin/build

.2021:kotlin:
  extends: .gradle
  only:
    changes:
      - 2021/kotlin/**/*
  cache:
    key: !reference [.2021:kotlin:caches, key]
    policy: pull
    paths: !reference [.2021:kotlin:caches, paths]

2021:kotlin:compile:
  extends:
    - .2021:kotlin
    - .gradle:compile
  cache:
    key: !reference [.2021:kotlin:caches, key]
    policy: pull-push
    paths: !reference [.2021:kotlin:caches, paths]

2021:kotlin:test:
  extends:
    - .2021:kotlin
    - .gradle:test
  dependencies:
    - 2021:kotlin:compile
  needs:
    - 2021:kotlin:compile
  artifacts:
    reports:
      junit: 2021/kotlin/build/test-results/test/TEST-*.xml

2021:kotlin:run:
  extends: .2021:kotlin
  stage: run
  dependencies:
    - 2021:kotlin:compile
  needs:
    - 2021:kotlin:compile
    - 2021:kotlin:test
  script:
    - java -jar 2021/kotlin/build/libs/aoc2021-shaded.jar --hide
