.2021:kotlin:
  extends: .maven
  before_script:
    - cd 2021/kotlin
  cache:
    key: '2021:kotlin'
    policy: pull
    paths:
      - 2021/kotlin/.m2/repository/
      - 2021/kotlin/target/

2021:kotlin:compile:
  extends:
    - .2021:kotlin
    - .maven:compile
  cache:
    key: '2021:kotlin'
    policy: pull-push
    paths:
      - 2021/kotlin/.m2/repository/
      - 2021/kotlin/target/

2021:kotlin:test:
  extends:
    - .2021:kotlin
    - .maven:test
  dependencies:
    - 2021:kotlin:compile
  needs:
    - 2021:kotlin:compile
  artifacts:
    reports:
      junit: 2021/kotlin/target/surefire-reports/TEST-*.xml

2021:kotlin:run:
  extends: .2021:kotlin
  stage: run
  dependencies:
    - 2021:kotlin:compile
  needs:
    - 2021:kotlin:compile
    - 2021:kotlin:test
  script:
    - java -jar target/adventofcode.2021-1.0.0-SNAPSHOT-jar-with-dependencies.jar
